"""initial schema

Revision ID: 1f9df8e705db
Revises:
Create Date: 2026-04-08 21:05:55.553455

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = "1f9df8e705db"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "action_log",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("action_type", sa.String(length=8), nullable=False),
        sa.Column("entity_type", sa.String(length=16), nullable=False),
        sa.Column("entity_id", sa.Integer(), nullable=False),
        sa.Column("before_state", sqlite.JSON(), nullable=True),
        sa.Column("after_state", sqlite.JSON(), nullable=True),
        sa.Column("batch_id", sa.String(length=36), nullable=False),
        sa.Column("is_undone", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("action_log", schema=None) as batch_op:
        batch_op.create_index("ix_action_log_batch_id", ["batch_id"], unique=False)
        batch_op.create_index("ix_action_log_entity", ["entity_type", "entity_id"], unique=False)
        batch_op.create_index("ix_action_log_undone_created", ["is_undone", "created_at"], unique=False)

    op.create_table(
        "chat_messages",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column("tool_calls", sqlite.JSON(), nullable=True),
        sa.Column("tool_results", sqlite.JSON(), nullable=True),
        sa.Column("telegram_message_id", sa.BigInteger(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("chat_messages", schema=None) as batch_op:
        batch_op.create_index("ix_chat_messages_created_at", ["created_at"], unique=False)

    op.create_table(
        "inbox_items",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("raw_text", sa.Text(), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("proposed_actions", sqlite.JSON(), nullable=True),
        sa.Column("batch_id", sa.String(length=36), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("inbox_items", schema=None) as batch_op:
        batch_op.create_index("ix_inbox_items_batch_id", ["batch_id"], unique=False)
        batch_op.create_index("ix_inbox_items_created_at", ["created_at"], unique=False)
        batch_op.create_index("ix_inbox_items_status", ["status"], unique=False)

    op.create_table(
        "settings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("wake_time", sa.String(length=5), nullable=False),
        sa.Column("wind_down_time", sa.String(length=5), nullable=False),
        sa.Column("notification_level", sa.String(length=16), nullable=False),
        sa.Column("auto_approve_mode", sa.String(length=16), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("areas", sqlite.JSON(), nullable=False),
        sa.Column("memory", sqlite.JSON(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "tags",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("area", sa.String(length=100), nullable=True),
        sa.Column("start_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("location", sa.String(length=500), nullable=True),
        sa.Column("is_all_day", sa.Boolean(), nullable=False),
        sa.Column("calendar_source", sa.String(length=16), nullable=False),
        sa.Column("external_id", sa.String(length=255), nullable=True),
        sa.Column("recurrence_rule", sa.String(length=500), nullable=True),
        sa.Column("inbox_item_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["inbox_item_id"],
            ["inbox_items.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("calendar_source", "external_id", name="uq_events_source_external_id"),
    )
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.create_index("ix_events_area", ["area"], unique=False)
        batch_op.create_index("ix_events_inbox_item_id", ["inbox_item_id"], unique=False)
        batch_op.create_index("ix_events_start_end", ["start_at", "end_at"], unique=False)

    op.create_table(
        "tasks",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("area", sa.String(length=100), nullable=True),
        sa.Column("priority", sa.String(length=8), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("time_estimate_minutes", sa.Integer(), nullable=True),
        sa.Column("recurrence_rule", sa.String(length=500), nullable=True),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("inbox_item_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["inbox_item_id"],
            ["inbox_items.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("tasks", schema=None) as batch_op:
        batch_op.create_index("ix_tasks_due_at", ["due_at"], unique=False)
        batch_op.create_index("ix_tasks_inbox_item_id", ["inbox_item_id"], unique=False)
        batch_op.create_index("ix_tasks_scheduled_at", ["scheduled_at"], unique=False)
        batch_op.create_index("ix_tasks_status_area", ["status", "area"], unique=False)
        batch_op.create_index("ix_tasks_status_due_at", ["status", "due_at"], unique=False)

    op.create_table(
        "subtasks",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("is_complete", sa.Boolean(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("subtasks", schema=None) as batch_op:
        batch_op.create_index("ix_subtasks_task_id", ["task_id"], unique=False)

    op.create_table(
        "task_tags",
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["tag_id"], ["tags.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("task_id", "tag_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("task_tags")
    with op.batch_alter_table("subtasks", schema=None) as batch_op:
        batch_op.drop_index("ix_subtasks_task_id")

    op.drop_table("subtasks")
    with op.batch_alter_table("tasks", schema=None) as batch_op:
        batch_op.drop_index("ix_tasks_status_due_at")
        batch_op.drop_index("ix_tasks_status_area")
        batch_op.drop_index("ix_tasks_scheduled_at")
        batch_op.drop_index("ix_tasks_inbox_item_id")
        batch_op.drop_index("ix_tasks_due_at")

    op.drop_table("tasks")
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.drop_index("ix_events_start_end")
        batch_op.drop_index("ix_events_inbox_item_id")
        batch_op.drop_index("ix_events_area")

    op.drop_table("events")
    op.drop_table("tags")
    op.drop_table("settings")
    with op.batch_alter_table("inbox_items", schema=None) as batch_op:
        batch_op.drop_index("ix_inbox_items_status")
        batch_op.drop_index("ix_inbox_items_created_at")
        batch_op.drop_index("ix_inbox_items_batch_id")

    op.drop_table("inbox_items")
    with op.batch_alter_table("chat_messages", schema=None) as batch_op:
        batch_op.drop_index("ix_chat_messages_created_at")

    op.drop_table("chat_messages")
    with op.batch_alter_table("action_log", schema=None) as batch_op:
        batch_op.drop_index("ix_action_log_undone_created")
        batch_op.drop_index("ix_action_log_entity")
        batch_op.drop_index("ix_action_log_batch_id")

    op.drop_table("action_log")
    # ### end Alembic commands ###
